name: Update Tags on Existing Data
on:
  schedule:
    - cron: "0 16 * * *"  # Runs daily at 4:00 PM UTC (11:00 PM UTC+7)
  workflow_dispatch:

jobs:
  update_tags_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updating pipeline
        run: python -m scripts.update_existing_tags
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_KEY: ${{ secrets.DB_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GROQ_API_KEY1: ${{ secrets.GROQ_API_KEY1 }}
          GROQ_API_KEY2: ${{ secrets.GROQ_API_KEY2 }}
          GROQ_API_KEY3: ${{ secrets.GROQ_API_KEY3 }}
          GROQ_API_KEY4: ${{ secrets.GROQ_API_KEY4 }}
          PROXY: ${{ secrets.PROXY }}

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Updated Tags on Existing Data" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}